# Generated by Django 5.1.7 on 2025-03-26 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(help_text='Tema principal de la charla.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la charla.', null=True)),
                ('fecha', models.DateField(help_text='Fecha en la que se realizará la charla.')),
                ('hora', models.TimeField(help_text='Hora de inicio de la charla.')),
                ('actividades', models.TextField(blank=True, help_text='Descripción de las actividades que se realizarán en la charla.', null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen opcional para la charla.', null=True, upload_to='charlas/')),
                ('quien_dara_la_charla', models.CharField(help_text='Nombre de la persona que dará la charla.', max_length=255)),
                ('ubicacion', models.CharField(help_text='Ubicación de la charla.', max_length=255)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', help_text='Modalidad de la charla (Presencial o Virtual).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la charla.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación de la charla.')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la charla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charla_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que modificó la charla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charla_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(help_text='Tema principal del conversatorio.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del conversatorio.', null=True)),
                ('fecha', models.DateField(help_text='Fecha en la que se realizará el conversatorio.')),
                ('hora', models.TimeField(help_text='Hora de inicio del conversatorio.')),
                ('moderador', models.CharField(help_text='Nombre del moderador del conversatorio.', max_length=255)),
                ('ubicacion', models.CharField(help_text='Ubicación del conversatorio.', max_length=255)),
                ('imagen', models.ImageField(help_text='Imagen opcional para el conversatorio.', upload_to='conversatorios/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del conversatorio.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del conversatorio.')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el conversatorio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversatorio_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que modificó el conversatorio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversatorio_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del evento.', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del evento.', null=True)),
                ('fecha', models.DateField(help_text='Fecha en la que se realizará el evento.')),
                ('hora', models.TimeField(help_text='Hora en la que se realizará el evento.')),
                ('lugar', models.CharField(help_text='Ubicación donde se llevará a cabo el evento.', max_length=200)),
                ('organizador', models.CharField(blank=True, help_text='Nombre del organizador del evento.', max_length=100, null=True)),
                ('imagen', models.ImageField(help_text='Imagen del evento.', upload_to='eventos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del evento.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del evento.')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que modificó el evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del evento de adopción.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del evento de adopción.', null=True)),
                ('fecha', models.DateField(help_text='Fecha de inicio del evento.')),
                ('hora', models.TimeField(help_text='Hora de inicio del evento.')),
                ('actividades', models.TextField(blank=True, help_text='Descripción de las actividades realizadas durante la jornada.', null=True)),
                ('tipo_evento', models.CharField(choices=[('Animales Fest', 'Animales Fest'), ('Huella con Historia', 'Huella con Historia'), ('Expo Amor', 'Expo Amor'), ('Festivales', 'Festivales'), ('Expo', 'Expo')], help_text='Tipo de evento (Animales Fest, Expo, etc.).', max_length=255)),
                ('ubicacion', models.CharField(help_text='Ubicación del evento de adopción.', max_length=255)),
                ('imagen', models.ImageField(help_text='Imagen opcional para la jornada de adopción.', upload_to='jornadas_adopcion/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la jornada de adopción.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación de la jornada de adopción.')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la jornada de adopción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadaadopcion_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que modificó la jornada de adopción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadaadopcion_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del taller.', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del taller.', null=True)),
                ('fecha', models.DateField(help_text='Fecha en la que se realizará el taller.')),
                ('hora', models.TimeField(help_text='Hora de inicio del taller.')),
                ('lugar', models.CharField(help_text='Lugar donde se realizará el taller.', max_length=255)),
                ('imagen', models.ImageField(help_text='Imagen opcional para el taller.', upload_to='talleres/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del taller.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del taller.')),
                ('created_by', models.ForeignKey(help_text='Usuario que creó el taller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que modificó el taller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
