# Generated by Django 5.1.7 on 2025-03-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='updated_at',
            new_name='actualizado_el',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='created_at',
            new_name='creado_el',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='evento',
            name='actualizado_por',
            field=models.ForeignKey(help_text='Usuario que modificó el evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó el evento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evento_creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
