# Generated by Django 5.1.7 on 2025-03-26 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_rename_updated_at_evento_actualizado_el_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='charla',
            old_name='updated_at',
            new_name='actualizado_el',
        ),
        migrations.RenameField(
            model_name='charla',
            old_name='created_at',
            new_name='creado_el',
        ),
        migrations.RemoveField(
            model_name='charla',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='charla',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='charla',
            name='actualizado_por',
            field=models.ForeignKey(help_text='Usuario que modificó la charla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charla_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charla',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó la charla.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charla_creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
