# Generated by Django 5.1.7 on 2025-03-26 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_rename_updated_at_charla_actualizado_el_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='taller',
            old_name='updated_at',
            new_name='actualizado_el',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='taller',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='taller',
            name='actualizado_por',
            field=models.ForeignKey(help_text='Usuario que modificó el taller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taller',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del taller.'),
        ),
        migrations.AddField(
            model_name='taller',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó el taller.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taller_creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
