# Generated by Django 5.1.7 on 2025-03-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_rename_updated_at_taller_actualizado_el_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del taller .'),
        ),
    ]
