# Generated by Django 5.1.7 on 2025-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0006_remove_conversatorio_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversatorio',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del taller .'),
        ),
    ]
