# Generated by Django 5.1.7 on 2025-03-26 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_conversatorio_creado_el'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornadaadopcion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jornadaadopcion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jornadaadopcion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='jornadaadopcion',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='jornadaadopcion',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del jornada.'),
        ),
        migrations.AddField(
            model_name='jornadaadopcion',
            name='actualizado_por',
            field=models.ForeignKey(help_text='Usuario que modificó el jornada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornada_actualizado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jornadaadopcion',
            name='creado_el',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de creación del taller.'),
        ),
        migrations.AddField(
            model_name='jornadaadopcion',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó el jornada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornada_creado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
