# Generated by Django 5.1.7 on 2025-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_remove_jornadaadopcion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornadaadopcion',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del jornada .'),
        ),
    ]
