# Generated by Django 5.1.7 on 2025-03-26 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la especie, por ejemplo: Perro, Gato, Conejo.', max_length=50, unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del especie.')),
                ('actualizado_el', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del especie.')),
                ('actualizado_por', models.ForeignKey(help_text='Usuario que modificó el especie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especie_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el especie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='especie_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
