# Generated by Django 5.1.7 on 2025-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_animal_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='categoria_edad',
            field=models.CharField(choices=[('Cachorro', 'Cachorro (0-1 año)'), ('Joven', 'Joven (1-3 años)'), ('Adulto', 'Adulto (3-8 años)'), ('Senior', 'Senior (8 años o más)')], default='Adulto', help_text='Categoría de edad del animal.', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(blank=True, help_text='Edad exacta en años del animal (si se conoce).', null=True),
        ),
    ]
