# Generated by Django 5.1.7 on 2025-04-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0003_animal_categoria_edad_alter_animal_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='categoria_edad',
            field=models.CharField(choices=[('Cachorro (0-1 año)', 'Cachorro (0-1 año)'), ('Joven (1-3 años)', 'Joven (1-3 años)'), ('Adulto (3-8 años)', 'Adulto (3-8 años)'), ('Senior (8 años o más)', 'Senior (8 años o más)')], help_text='Categoría de edad del animal.', max_length=21),
        ),
    ]
