# Generated by Django 5.1.7 on 2025-03-28 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(help_text="Ingresa la pregunta que quieres hacer (por ejemplo, '¿Cómo puedo registrarme?').", max_length=255)),
                ('respuesta', models.TextField(help_text='Escribe la respuesta a la pregunta (puede ser detallada).')),
                ('creado_el', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del especie.')),
                ('actualizado_el', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del especie.')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
