"""
Django settings for la_quiltra project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

import environ
import cloudinary
import cloudinary.uploader
import cloudinary.api

env = environ.Env()
environ.Env.read_env()

cloudinary.config(
    cloud_name=env('CLOUDINARY_CLOUD_NAME'),
    api_key=env('CLOUDINARY_API_KEY'),
    api_secret=env('CLOUDINARY_API_SECRET'),
    secure=True
)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='dev-key')
DEBUG = env.bool('DEBUG', default=True)
ALLOWED_HOSTS = ['localhost', '127.0.0.1']



# settings.py

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'cloudinary_storage',
    'actividades',
    'animales',
    'galeria',
    'nosotros',
    'preguntas',
]

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'la_quiltra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'la_quiltra.wsgi.application'

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
import pymysql
pymysql.install_as_MySQLdb()
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(default=env('DATABASE_URL'))
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Ruta de los archivos estáticos
STATIC_URL = '/static/'

# Si estás en un entorno de producción, debes usar esta configuración
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'kelsregla@gmail.com'
EMAIL_HOST_PASSWORD = 'sfru osjs dean lifx'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if os.environ.get('RENDER'):
    DEBUG = False
    ALLOWED_HOSTS += ['tu-app.onrender.com']
    CSRF_TRUSTED_ORIGINS = ['https://tu-app.onrender.com', 'https://lacasaquiltra.com']
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


JAZZMIN_SETTINGS = {
    # Títulos y encabezados
    "site_title": "Panel de Administración",
    "site_header": "Administración de Animales y Adopciones",
    "site_brand": "La Quiltra",
    "welcome_sign": "Bienvenido a la administración de adopciones",
    "custom_css": "css/custom_admin.css",

    # UI Builder (Opcional)
    "show_ui_builder": True,  

    # Personalización de estilos e iconos
    "custom_css": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css",  # Carga FontAwesome 5
    "default_icon": "fas fa-paw",  

    # Configuración del menú lateral
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": ["sessions"],
    "hide_models": ["auth.Permission"],
    "order_with_respect_to": ["auth", "galeria", "nosotros", "preguntas", "animales", "actividades"],

    # Iconos personalizados por app
    "icons": {
        # Autenticación y usuarios
        "auth": "fas fa-user-shield",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",

        # 📷 Galería
        "galeria.Galeria": "fas fa-images",

        # 🏠 Nosotros
        "nosotros.SobreNosotros": "fas fa-info-circle",
        "nosotros.InformacionContacto": "fas fa-address-book",
        "nosotros.MensajeContacto": "fas fa-envelope",
        "nosotros.MiembroEquipo": "fas fa-user-friends",
        "nosotros.Voluntario": "fas fa-handshake",  


        # ❓ Preguntas
        "preguntas.Pregunta": "fas fa-question-circle",

        # 🐾 Animales
        "animales.Animal": "fas fa-paw",
        "animales.HistorialMedico": "fas fa-file-medical",
        "animales.especie": "fas fa-book", 

        # 🎭 Actividades
        "actividades.Evento": "fas fa-calendar-alt",
        "actividades.Charla": "fas fa-comments",
        "actividades.Taller": "fas fa-chalkboard-teacher",
        "actividades.Conversatorio": "fas fa-comment-dots",
        "actividades.JornadaAdopcion": "fas fa-hand-holding-heart",
    },
    
    # Pie de página
    "copyright": "La Casa de la Quiltra  © 2025",
    "version": "1.0.0",
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-purple",
    "accent": "accent-purple",
    "navbar": "navbar-purple navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-purple",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
