# Generated by Django 5.1.7 on 2025-03-28 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(help_text='Dirección del refugio', max_length=255)),
                ('telefono', models.CharField(help_text='Número de teléfono del refugio', max_length=15)),
                ('email', models.EmailField(help_text='Correo electrónico de contacto', max_length=254)),
                ('horario_lunes_sabado', models.CharField(help_text='Horario de lunes a sábado', max_length=50)),
                ('horario_domingo', models.CharField(help_text='Horario de domingo', max_length=50)),
                ('facebook', models.URLField(help_text='Enlace a Facebook', max_length=255)),
                ('instagram', models.URLField(help_text='Enlace a Instagram', max_length=255)),
                ('tiktok', models.URLField(help_text='Enlace a TikTok', max_length=255)),
                ('esponsor_enlace', models.URLField(help_text='Enlace de Esponsor', max_length=255)),
                ('creado_el', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del especie.')),
                ('actualizado_el', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del especie.')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informacioncontacto_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informacioncontacto_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Información de Contacto',
                'verbose_name_plural': 'Información de Contacto',
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(help_text='Nombre de la persona que contacta', max_length=255)),
                ('email_usuario', models.EmailField(help_text='Correo electrónico de la persona que contacta', max_length=254)),
                ('asunto', models.CharField(help_text='Asunto del mensaje', max_length=255)),
                ('mensaje', models.TextField(help_text='Cuerpo del mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se envió el mensaje')),
                ('creado_el', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del especie.')),
                ('actualizado_el', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del especie.')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajedecontacto_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajedecontacto_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa el nombre completo del miembro del equipo', max_length=100)),
                ('rol', models.CharField(help_text='Ingresa el rol del miembro dentro del equipo (Ej: Fundadora, Veterinario, etc.)', max_length=100)),
                ('cargo', models.CharField(help_text='Especifica el cargo o puesto específico del miembro (Ej: Coordinadora, Voluntario, etc.)', max_length=100)),
                ('imagen', models.ImageField(help_text='Sube la imagen para los Miembros.', upload_to='miembros/')),
                ('creado_el', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del especie.')),
                ('actualizado_el', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del especie.')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SobreNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_refugio', models.CharField(default='Refugio de Animales', max_length=255)),
                ('historia', models.TextField(help_text='Historia sobre la fundación del refugio')),
                ('mision', models.TextField(help_text='Misión del refugio')),
                ('vision', models.TextField(help_text='Visión del refugio')),
                ('fecha_fundacion', models.DateField(default='2015-01-01', help_text='Fecha de fundación del refugio')),
                ('animales_rescatados', models.PositiveIntegerField(blank=True, default=1000, help_text='Número de animales rescatados y reubicados', null=True)),
                ('imagen', models.ImageField(help_text='Imagen representativa del refugio.', upload_to='sobre_nosotros/')),
                ('creado_el', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del especie.')),
                ('actualizado_el', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del especie.')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosotros_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nosotros_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sobre Nosotros',
                'verbose_name_plural': 'Sobre Nosotros',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del voluntario.', max_length=100)),
                ('contacto', models.CharField(help_text='Teléfono o correo de contacto.', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico del voluntario.', max_length=254)),
                ('fecha_registro', models.DateField(auto_now_add=True, help_text='Fecha en la que el voluntario se registró.')),
                ('disponibilidad', models.CharField(choices=[('Fines de semana', 'Fines de semana'), ('Entre semana', 'Entre semana'), ('Tiempo completo', 'Tiempo completo')], help_text='Disponibilidad del voluntario.', max_length=50)),
                ('habilidades', models.TextField(help_text='Habilidades o experiencia del voluntario.')),
                ('imagen', models.ImageField(help_text='Imagen del voluntario.', upload_to='voluntarios/')),
                ('creado_el', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del especie.')),
                ('actualizado_el', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación del especie.')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntario_actualizado_por', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voluntario_creado_por', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
