# Generated by Django 5.1.7 on 2025-03-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembroequipo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube la imagen para los Miembros.', null=True, upload_to='miembros/'),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del refugio.', null=True, upload_to='sobre_nosotros/'),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='nombre_refugio',
            field=models.CharField(default='La casa de la Quiltra', help_text='Nombre del refugio', max_length=255),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del voluntario.', null=True, upload_to='voluntarios/'),
        ),
    ]
