# Generated by Django 5.1.7 on 2025-03-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0002_alter_miembroequipo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrenosotros',
            name='fecha_fundacion',
            field=models.DateField(blank=True, default='2015-01-01', help_text='Fecha de fundación del refugio', null=True),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='historia',
            field=models.TextField(blank=True, help_text='Historia sobre la fundación del refugio', null=True),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='mision',
            field=models.TextField(blank=True, help_text='Misión del refugio', null=True),
        ),
        migrations.AlterField(
            model_name='sobrenosotros',
            name='vision',
            field=models.TextField(blank=True, help_text='Visión del refugio', null=True),
        ),
    ]
